apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJzaGViYXBheS5henVyZWNyLmlvIjogewogICAgICAiYXV0aCI6ICJjMmhsWW1Gd1lYazZTV0YyVjNVMmRtVjNOMXA0ZWtGelp6QXlMelI2Y2tGbmJWcDNXbUVyTUcxUmRGcFZTekpXTTNGWUswRkRVa1JWVEhWNVZ3PT0iLAogICAgICAiZW1haWwiOiAiZmludGVjaC1iczIzQGJzdGF0aW9uMjMub25taWNyb3NvZnQuY29tIgogICAgfQogIH0KfQ==
kind: Secret
metadata:
  creationTimestamp: "2022-09-21T07:12:20Z"
  name: azure-registry-secret-dmz
  namespace: dmz
  resourceVersion: "4279"
  uid: 0f89eeea-ae63-495b-880b-df89d47f0b99
type: kubernetes.io/dockerconfigjson