apiVersion: v1
kind: ConfigMap
metadata:
  name: charge-config-service
  namespace: mz
data:
  CHARGE_CONFIG_REDIS_POOL_MAX_CONNECTION: '10'
  CHARGE_CONFIG_REDIS_POOL_MAX_IDLE_CONNECTION: '5'
  CHARGE_CONFIG_REDIS_POOL_MIN_IDLE_CONNECTION: '0'
  CHARGE_CONFIG_SERVICE_BD_PASSWORD: sheba@123
  CHARGE_CONFIG_SERVICE_BD_USERNAME: shebawallet
  CHARGE_CONFIG_SERVICE_DB_URL: jdbc:postgresql://10.34.13.11:5432/sheba_wallet_db?currentSchema=charge-config
  CHARGE_CONFIG_SERVICE_FLYWAY_PASSWORD: sheba@123
  CHARGE_CONFIG_SERVICE_FLYWAY_SCHEMA: charge-config
  CHARGE_CONFIG_SERVICE_FLYWAY_URL: jdbc:postgresql://10.33.13.11:5432/sheba_wallet_db
  CHARGE_CONFIG_SERVICE_FLYWAY_USER: shebawallet
  CHARGE_CONFIG_SERVICE_LOGBACK_FILE: classpath:log/logback-uat.xml
  CHARGE_CONFIG_SERVICE_REDIS_HOST: redis-master.redis.svc.cluster.local
  CHARGE_CONFIG_SERVICE_REDIS_PASSWORD:  Sheba@1234
  CHARGE_CONFIG_SERVICE_REDIS_PORT: '6379'
  CHARGE_CONFIG_SERVICE_SERVER_PORT: '8904'
  CHARGE_CONFIG_SERVICE_SLEUTH_SAMPLER_PROBABILITY: '1.0'
  CHARGE_CONFIG_SERVICE_ZONE:  http://eureka-sts-0.eureka.dmz.svc.cluster.local:8761/eureka,http://eureka-sts-1.eureka.dmz.svc.cluster.local:8761/eureka,http://eureka-sts-2.eureka.dmz.svc.cluster.local:8761/eureka
  WALLET_GATEWAY_URL: https://dr-api.shebapay.xyz
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: charge-config-service
  namespace: mz
  labels:
    app: charge-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: charge-config-service
  template:
    metadata:
      labels:
        app: charge-config-service
    spec:
      imagePullSecrets:
      - name: azure-registry-secret-mz
      containers:
      - name: charge-config-service
        envFrom:
        - configMapRef:
            name: charge-config-service
        image: shebapay.azurecr.io/shebapay/charge-config-service:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        ports:
        - containerPort: 8904
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8904
          initialDelaySeconds: 240
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8904
          initialDelaySeconds: 240
          periodSeconds: 3


        
---

apiVersion: v1
kind: Service
metadata:
  name: charge-config-service-svc
  namespace: mz
spec:
  selector:
    app: charge-config-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8904
 