apiVersion: v1
kind: ConfigMap
metadata:
  name: file-server-service
  namespace: mz
data:
  FILE_SERVER_SERVICE_DATASOURCE_PASSWORD: sheba@123
  FILE_SERVER_SERVICE_DATASOURCE_URL: jdbc:postgresql://10.34.13.11:5432/sheba_wallet_db?currentSchema=file-server
  FILE_SERVER_SERVICE_DATASOURCE_USERNAME: shebawallet
  FILE_SERVER_SERVICE_IMAGE_EXPIRY_SECRET_KEY: __bs@23EE32@sb__
  FILE_SERVER_SERVICE_IMAGE_FILE_SECRET_KEY: __bs@23FF32@sb__
  FILE_SERVER_SERVICE_LOGGING_CONFIG: classpath:log/logback-uat.xml
  FILE_SERVER_SERVICE_PORT: '8907'
  FILE_SERVER_SERVICE_REDIS_HOST: redis-master.redis.svc.cluster.local
  FILE_SERVER_SERVICE_REDIS_MAX_CONNECTION: '30'
  FILE_SERVER_SERVICE_REDIS_MAX_IDLE_CONNECTION: '10'
  FILE_SERVER_SERVICE_REDIS_MIN_IDLE_CONNECTION: '0'
  FILE_SERVER_SERVICE_REDIS_PASSWORD: Sheba@1234
  FILE_SERVER_SERVICE_REDIS_PORT: '6379'
  FILE_SERVER_SERVICE_SEAWEED_MASTER_URL: http://10.34.11.250:9333
  FILE_SERVER_SERVICE_SEAWEED_SERVICE_URL: http://10.34.11.250:5080
  FILE_SERVER_SERVICE_SLEUTH_SAM_PRO: '1.0'
  FILE_SERVER_SERVICE_ZONE: http://eureka-sts-0.eureka.dmz.svc.cluster.local:8761/eureka,http://eureka-sts-1.eureka.dmz.svc.cluster.local:8761/eureka,http://eureka-sts-2.eureka.dmz.svc.cluster.local:8761/eureka
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-service
  namespace: mz
  labels:
    app: file-server-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-server-service
  template:
    metadata:
      labels:
        app: file-server-service
    spec:
      imagePullSecrets:
      - name: azure-registry-secret-mz
      containers:
      - name: file-server-service
        envFrom:
        - configMapRef:
            name: file-server-service
        image: shebapay.azurecr.io/shebapay/file-server-service:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        ports:
        - containerPort: 8907
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8907
          initialDelaySeconds: 240
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8907
          initialDelaySeconds: 240
          periodSeconds: 3


        
---

apiVersion: v1
kind: Service
metadata:
  name: file-server-service-svc
  namespace: mz
spec:
  selector:
    app: file-server-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8907
 