apiVersion: v1
kind: ConfigMap
metadata:
  name: fineract-provider 
  namespace: mz
data:
  FINERACT_DEFAULT_TENANTDB_HOSTNAME: '10.34.13.11'
  FINERACT_DEFAULT_TENANTDB_PORT: '5432'
  FINERACT_DEFAULT_TENANTDB_UID: shebawallet
  FINERACT_DEFAULT_TENANTDB_PWD: sheba@123
  FINERACT_DEFAULT_TENANTDB_IDENTIFIER: sheba_pay
  FINERACT_DEFAULT_TENANTDB_NAME: bs23_wallet_shebapay
  FINERACT_DEFAULT_TENANTDB_DESCRIPTION: Default Tenant
  FINERACT_SERVER_SERVLET_CONTEXT_PATH: /fineract-provider
  FINERACT_SERVER_JWT_ISSUER_URI: http://localhost:9000/auth/realms/fineract
  FINERACT_HIKARI_DRIVER_SOURCE_CLASS_NAME: org.postgresql.Driver
  FINERACT_HIKARI_JDBC_URL: jdbc:postgresql://10.34.13.11:5432/bs23_wallet_tenants
  FINERACT_HIKARI_USERNAME: shebawallet
  FINERACT_HIKARI_PASSWORD: sheba@123

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fineract-provider
  namespace: mz
  labels:
    app: fineract-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fineract-provider
  template:
    metadata:
      labels:
        app: fineract-provider
    spec:
      imagePullSecrets:
      - name: azure-registry-secret-mz
      containers:
      - name:  fineract-provider
        envFrom:
        - configMapRef:
            name:  fineract-provider
        image: shebapay.azurecr.io/shebapay/fineract-provider:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8443
        livenessProbe:
          httpGet:
            path: fineract-provider/actuator/health/liveness
            port: 8443
          initialDelaySeconds: 180
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: fineract-provider/actuator/health/readiness
            port: 8443
          initialDelaySeconds: 180
          periodSeconds: 3


        
---

apiVersion: v1
kind: Service
metadata:
  name: fineract-provider-svc
  namespace: mz
spec:
  selector:
    app: fineract-provider
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8443
 
