apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service 
  namespace: mz
data:
  NOTIFICATION_SERVICE_PORT: '8912'
  NOTIFICATION_SERVICE_ZONE:  http://eureka-sts-0.eureka.dmz.svc.cluster.local:8761/eureka,http://eureka-sts-1.eureka.dmz.svc.cluster.local:8761/eureka,http://eureka-sts-2.eureka.dmz.svc.cluster.local:8761/eureka
  NOTIFICATION_SERVICE_SLEUTH_SAM_PRO: '1.0'
  NOTIFICATION_SERVICE_DATASOURCE_URL: jdbc:postgresql://10.34.13.11:5432/sheba_wallet_db?currentSchema=notification
  NOTIFICATION_SERVICE_DATASOURCE_USERNAME: shebawallet
  NOTIFICATION_SERVICE_DATASOURCE_PASSWORD: sheba@123
  NOTIFICATION_SERVICE_MAIL_HOST: smtp.gmail.com
  NOTIFICATION_SERVICE_MAIL_PORT: '587'
  NOTIFICATION_SERVICE_MAIL_USERNAME: shahinbeg80@gmail.com
  NOTIFICATION_SERVICE_MAIL_PASSWORD: zstnslhqoiprmdmh
  NOTIFICATION_SERVICE_REDIS_HOST: redis-master.redis.svc.cluster.local
  NOTIFICATION_SERVICE_REDIS_PORT: '6379'
  NOTIFICATION_SERVICE_REDIS_PASSWORD: Sheba@1234
  NOTIFICATION_SERVICE_REDIS_MAX_CONNECTION: '30'
  NOTIFICATION_SERVICE_REDIS_MAX_IDLE_CONNECTION: '2'
  NOTIFICATION_SERVICE_REDIS_MIN_IDLE_CONNECTION: '0'
  NOTIFICATION_SERVICE_LOGGING_CONFIG: classpath:log/logback-uat.xml
  NOTIFICATION_SERVICE_SSL_SMS_API_TOKEN: rmiwsmly-i2htfqwk-v2ly7o3o-mxkromd2-qsczwtws
  NOTIFICATION_SERVICE_SSL_SMS_API_TOKEN_OPERATOR_OTHER: ABGNONAPI
  NOTIFICATION_SERVICE_SSL_SMS_API_TOKEN_OPERATOR_GP: ABGNONAPI
  NOTIFICATION_SERVICE_NOT_TEMP_COMM_SMS_TOKEN: "IGJlYdTAobC"
  NOTIFICATION_SERVICE_MERCHANT_COMM_SMS_TOKEN: QDLcZwCnhKH
  NOTIFICATION_SERVICE_CUSTOMER_COMM_SMS_TOKEN: 1GmKF0hzm89
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: mz
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      imagePullSecrets:
      - name: azure-registry-secret-mz
      containers:
      - name: notification-service
        envFrom:
        - configMapRef:
            name:  notification-service
        image: shebapay.azurecr.io/shebapay/notification-service:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        ports:
        - containerPort: 8912
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8912
          initialDelaySeconds: 420
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8912
          initialDelaySeconds: 420
          periodSeconds: 3


        
---

apiVersion: v1
kind: Service
metadata:
  name: notification-service-svc
  namespace: mz
spec:
  selector:
    app: notification-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8912
 