apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-gateway-service
data:
  AD_GW_DB_PASS: sheba@123
  AD_GW_DB_URL: r2dbc:postgresql://10.33.13.11:5432/sheba_wallet_db?currentSchema=admin_gateway
  AD_GW_DB_USER: shebawallet
  AD_GW_EUREKA_PORT: '8761'
  AD_GW_EUREKA_URL: http://eureka-sts-0.eureka.default.svc.cluster.local:8761/eureka
  AD_GW_JWT_KEY: 327234753778214125442A472D4B6150645367566B59703373367638792F423F
  AD_GW_PORT: '8001'
  AD_GW_REDIS_HOST: redis-master.redis.svc.cluster.local
  AD_GW_REDIS_PASS: Sheba@1234
  AD_GW_REDIS_PORT: '6379'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-gateway-service
  labels:
    app: admin-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-gateway-service
  template:
    metadata:
      labels:
        app: admin-gateway-service
    spec:
      imagePullSecrets:
      - name: azure-registry-secret
      containers:
      - name: admin-gateway-service
        envFrom:
        - configMapRef:
            name: admin-gateway-service
        image: shebapay.azurecr.io/shebapay/admin-gateway-service:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        ports:
        - containerPort: 8001
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8001
          initialDelaySeconds: 240
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8001
          initialDelaySeconds: 240
          periodSeconds: 3


        
---

apiVersion: v1
kind: Service
metadata:
  name: admin-gateway-service-svc
spec:
  selector:
    app: admin-gateway-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8001
 
