apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
  labels:
    app: admin-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
    spec:
      imagePullSecrets:
      - name: azure-registry-secret
      containers:
      - name: admin-frontend
        env:
        - name: TZ
          value: Asia/Dhaka
        image: shebapay.azurecr.io/shebapay/sheba-admin-prod:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: admin-frontend-svc
spec:
  selector:
    app: admin-frontend
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
