apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-service
data:
  BANK_SERVICE_BD_PASSWORD: sheba@123
  BANK_SERVICE_BD_USERNAME: shebawallet
  BANK_SERVICE_DB_URL: jdbc:postgresql://10.33.13.11:5432/sheba_wallet_db?currentSchema=financial_institute
  BANK_SERVICE_LOGBACK_FILE: classpath:log/logback-uat.xml
  BANK_SERVICE_REDIS_HOST: redis-master.redis.svc.cluster.local
  BANK_SERVICE_REDIS_PASSWORD: Sheba@1234
  BANK_SERVICE_REDIS_PORT: '6379'
  BANK_SERVICE_SERVER_PORT: '8903'
  BANK_SERVICE_SLEUTH_SAMPLER_PROBABILITY: '1.0'
  BANK_SERVICE_ZONE: http://eureka-sts-0.eureka.default.svc.cluster.local:8761/eureka
  REDIS_POOL_MAX_CONNECTION: '30'
  REDIS_POOL_MAX_IDLE_CONNECTION: '10'
  REDIS_POOL_MIN_IDLE_CONNECTION: '0'
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
  labels:
    app: bank-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      imagePullSecrets:
      - name: azure-registry-secret
      containers:
      - name: bank-service
        envFrom:
        - configMapRef:
            name: bank-service
        image: shebapay.azurecr.io/shebapay/bank-service:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        ports:
        - containerPort: 8903
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8903
          initialDelaySeconds: 240
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8903
          initialDelaySeconds: 240
          periodSeconds: 3


        
---

apiVersion: v1
kind: Service
metadata:
  name: bank-service-svc
spec:
  selector:
    app: bank-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8903
 