apiVersion: v1
kind: ConfigMap
metadata:
  name: merchant-charge-config-service
data:
  MERCHANT_CHARGE_CONFIG_SERVICE_SERVER_PORT: '8914'
  MERCHANT_CHARGE_CONFIG_SERVICE_ZONE: http://eureka-sts-0.eureka.default.svc.cluster.local:8761/eureka
  MERCHANT_CHARGE_CONFIG_SERVICE_SLEUTH_SAMPLER_PROBABILITY: '1.0'
  MERCHANT_CHARGE_CONFIG_SERVICE_DB_URL: jdbc:postgresql://10.33.13.11:5432/sheba_wallet_db?currentSchema=merchant
  MERCHANT_CHARGE_CONFIG_SERVICE_DB_USERNAME: shebawallet
  MERCHANT_CHARGE_CONFIG_SERVICE_DB_PASSWORD: sheba@123
  MERCHANT_CHARGE_CONFIG_SERVICE_REDIS_HOST: redis-master.redis.svc.cluster.local
  MERCHANT_CHARGE_CONFIG_SERVICE_REDIS_PORT: '6379'
  MERCHANT_CHARGE_CONFIG_SERVICE_REDIS_PASSWORD: Sheba@1234
  MERCHANT_CHARGE_CONFIG_REDIS_POOL_MAX_CONNECTION: '30'
  MERCHANT_CHARGE_CONFIG_REDIS_POOL_MAX_IDLE_CONNECTION: '10'
  MERCHANT_CHARGE_CONFIG_REDIS_POOL_MIN_IDLE_CONNECTION: '0'
  MERCHANT_CHARGE_CONFIG_SERVICE_LOGBACK_FILE: classpath:log/logback-uat.xml
  WALLET_GATEWAY_URL: https://api.shebapay.xyz
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant-charge-config-service
  labels:
    app: merchant-charge-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merchant-charge-config-service
  template:
    metadata:
      labels:
        app: merchant-charge-config-service
    spec:
      imagePullSecrets:
      - name: azure-registry-secret
      containers:
      - name:  merchant-charge-config-service
        envFrom:
        - configMapRef:
            name:  merchant-charge-config-service
        image: shebapay.azurecr.io/shebapay/merchant-charge-config-service:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        ports:
        - containerPort: 8914
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8914
          initialDelaySeconds: 240
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8914
          initialDelaySeconds: 240
          periodSeconds: 3


        
---

apiVersion: v1
kind: Service
metadata:
  name: merchant-charge-config-service-svc
spec:
  selector:
    app: merchant-charge-config-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8914
 