apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service 
data:
  PAYMENT_SERVICE_PORT: '8913'
  PAYMENT_SERVICE_ZONE: http://eureka-sts-0.eureka.default.svc.cluster.local:8761/eureka
  PAYMENT_SERVICE_DATASOURCE_URL: jdbc:postgresql://10.33.13.11:5432/sheba_wallet_db?currentSchema=payment_service
  PAYMENT_SERVICE_DATASOURCE_USERNAME: shebawallet
  PAYMENT_SERVICE_DATASOURCE_PASSWORD: sheba@123
  PAYMENT_SERVICE_HIKARI_MAX_POOL_SIZE: '3'
  PAYMENT_SERVICE_HIKARI_MIN_IDLE: '1'
  PAYMENT_SERVICE_REDIS_HOST: redis-master.redis.svc.cluster.local
  PAYMENT_SERVICE_REDIS_PORT: '6379'
  PAYMENT_SERVICE_REDIS_PASSWORD: Sheba@1234
  PAYMENT_SERVICE_REDIS_DATABASE_INDEX: '12'
  PAYMENT_SERVICE_REDIS_MAX_CONNECTION: '30'
  PAYMENT_SERVICE_REDIS_MAX_IDLE_CONNECTION: '10'
  PAYMENT_SERVICE_REDIS_MIN_IDLE_CONNECTION: '0'
  PAYMENT_SERVICE_LOGGING_CONFIG: classpath:log/logback-uat.xml
  PAYMENT_SERVICE_HTTP_HEADER_AUTH: Authorization
  PAYMENT_SERVICE_HTTP_HEADER_LANGUAGE: Accept-Language
  PAYMENT_SERVICE_HTTP_HEADER_USERTYPE: User-Type
  PAYMENT_SERVICE_MOBILE_RECHARGE_BASE_URL: http://api.sslwireless.com/api
  PAYMENT_SERVICE_MOBILE_RECHARGE_AUTH_KEY: BD6pFSIfSOLEIgKyru67MeBhICkRiFla
  PAYMENT_SERVICE_MOBILE_RECHARGE_BASE_STK_CODE: DEMO
  PAYMENT_SERVICE_IMAGE_EXP_SECRET_KEY: __bs@23EE32@sb__
  PAYMENT_SERVICE_IMAGE_EXP_SECRET_MINUTES: '2'
  PAYMENT_SERVICE_WALLET_GATEWAY_URL: https://api.shebapay.xyz
  PAYMENT_SERVICE_INSTANT_NOTIFICATION_TIME: '10'
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      imagePullSecrets:
      - name: azure-registry-secret
      containers:
      - name: payment-service
        envFrom:
        - configMapRef:
            name:  payment-service
        image: shebapay.azurecr.io/shebapay/payment-service:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        ports:
        - containerPort: 8913
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8913
          initialDelaySeconds: 240
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8913
          initialDelaySeconds: 240
          periodSeconds: 3


        
---

apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
spec:
  selector:
    app: payment-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8913
 