apiVersion: v1
kind: ConfigMap
metadata:
  name: send-money-service 
data:
  PAYMENT_SERVICE_HIKARI_MAX_POOL_SIZE : '1'
  PAYMENT_SERVICE_HIKARI_MIN_IDLE : '1'
  SEND_MONEY_SERVICE_DATASOURCE_PASSWORD : sheba@123
  SEND_MONEY_SERVICE_DATASOURCE_URL : jdbc:postgresql://10.33.13.11:5432/sheba_wallet_db?currentSchema=send_money
  SEND_MONEY_SERVICE_DATASOURCE_USERNAME : shebawallet
  SEND_MONEY_SERVICE_LOGGING_CONFIG : classpath:log/logback-uat.xml
  SEND_MONEY_SERVICE_PORT : '8910'
  SEND_MONEY_SERVICE_REDIS_HOST : redis-master.redis.svc.cluster.local
  SEND_MONEY_SERVICE_REDIS_MAX_CONNECTION : '30'
  SEND_MONEY_SERVICE_REDIS_MAX_IDLE_CONNECTION : '2'
  SEND_MONEY_SERVICE_REDIS_MIN_IDLE_CONNECTION : '0'
  SEND_MONEY_SERVICE_REDIS_PASSWORD : Sheba@1234
  SEND_MONEY_SERVICE_REDIS_PORT : '6379'
  SEND_MONEY_SERVICE_SLEUTH_SAM_PRO : '1.0'
  SEND_MONEY_SERVICE_ZONE : http://eureka-sts-0.eureka.default.svc.cluster.local:8761/eureka,http://eureka-sts-1.eureka.default.svc.cluster.local:8761/eureka,http://eureka-sts-2.eureka.default.svc.cluster.local:8761/eureka
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-money-service
  labels:
    app: send-money-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send-money-service
  template:
    metadata:
      labels:
        app: send-money-service
    spec:
      imagePullSecrets:
      - name: azure-registry-secret
      containers:
      - name: send-money-service
        env:
        - name: TZ
          value: Asia/Dhaka
        envFrom:
        - configMapRef:
            name: send-money-service
        image: shebapay.azurecr.io/shebapay/send-money-service:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        ports:
        - containerPort: 8910
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8910
          initialDelaySeconds: 240
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8910
          initialDelaySeconds: 240
          periodSeconds: 3


        
---

apiVersion: v1
kind: Service
metadata:
  name: send-money-service-svc
spec:
  selector:
    app: send-money-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8910
 