apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-service
data:
  ADMIN_SERVICE_DATASOURCE_PASSWORD: p0cket@ABG
  ADMIN_SERVICE_DATASOURCE_URL: jdbc:postgresql://10.11.245.12:5432/wallet_db?currentSchema=admin
  ADMIN_SERVICE_DATASOURCE_USERNAME: pocket_uat
  ADMIN_SERVICE_HOST_URL: http://test-api.abgpocket.com/admin/
  ADMIN_SERVICE_JWT_KEY: 327234753778214125442A472D4B6150645367566B59703373367638792F423F
  ADMIN_SERVICE_LOGGING_CONFIG: classpath:log/logback-beta.xml
  ADMIN_SERVICE_PORT: '8902'
  ADMIN_SERVICE_REDIS_HOST: redis-1678904797-master.redis.svc.uat.pocket.local
  ADMIN_SERVICE_REDIS_MAX_CONNECTION: '30'
  ADMIN_SERVICE_REDIS_MAX_IDLE_CONNECTION: '2'
  ADMIN_SERVICE_REDIS_MIN_IDLE_CONNECTION: '0'
  ADMIN_SERVICE_REDIS_PASSWORD: p0cket@ABG
  ADMIN_SERVICE_REDIS_PORT: '6379'
  ADMIN_SERVICE_SLEUTH_SAM_PRO: '1.0'
  ADMIN_SERVICE_ZONE:  http://eureka-sts-0.eureka.default.svc.uat.pocket.local:8761/eureka

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  labels:
    app: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: admin-service
        envFrom:
        - configMapRef:
            name: admin-service
        image: 10.96.233.11:8888/pocket/admin-service:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        ports:
        - containerPort: 8902
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8902
          initialDelaySeconds: 120
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8902
          initialDelaySeconds: 120
          periodSeconds: 3


        
---

apiVersion: v1
kind: Service
metadata:
  name: admin-service-svc
spec:
  selector:
    app: admin-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8902
 