apiVersion: v1
kind: ConfigMap
metadata:
  name: core-service
data:
  CORE_SERVICE_DATASOURCE_PASSWORD: p0cket@ABG
  CORE_SERVICE_DATASOURCE_URL: jdbc:postgresql://10.11.245.12:5432/wallet_db?currentSchema=core
  CORE_SERVICE_DATASOURCE_USERNAME: pocket_uat
  CORE_SERVICE_FINERACT_AUTH_TOKEN: Basic bWlmb3M6cGFzc3dvcmQ=
  CORE_SERVICE_FINERACT_BASE_URL: http://10.11.245.11:8443/fineract-provider/api/v1
  CORE_SERVICE_LOGGING_CONFIG: classpath:log/logback-beta.xml
  CORE_SERVICE_MTB_REQUEST_HEADER_PASS: abg@12345
  CORE_SERVICE_MTB_REQUEST_HEADER_UNAME: abgLBuat
  CORE_SERVICE_MTB_SAND_BOX_BASE_URL: https://uat.mutualtrustbank.com/lbuat
  CORE_SERVICE_PORICHOY_AUTH_HEADER: x-api-key
  CORE_SERVICE_PORICHOY_AUTH_VALUE: 47f4852a-c08a-41a1-82f4-0a548812680e
  CORE_SERVICE_PORICHOY_BASE_URL: https://api.porichoybd.com
  CORE_SERVICE_PORT: '8905'
  CORE_SERVICE_REDIS_HOST: redis-1678904797-master.redis.svc.uat.pocket.local
  CORE_SERVICE_REDIS_MAX_CONNECTION: '30'
  CORE_SERVICE_REDIS_MAX_IDLE_CONNECTION: '2'
  CORE_SERVICE_REDIS_MIN_IDLE_CONNECTION: '0'
  CORE_SERVICE_REDIS_PASSWORD: p0cket@ABG
  CORE_SERVICE_REDIS_PORT: '6379'
  CORE_SERVICE_SLEUTH_SAM_PRO: '1.0'
  CORE_SERVICE_SSL_CARD_BASE_URL: https://sandbox.sslcommerz.com
  CORE_SERVICE_SSL_CARD_CALLBACK_URL: http://test-api.abgpocket.com/api/v1/add-money/call-back/ssl/card
  CORE_SERVICE_SSL_STORE_ID: brain63b170eaefd57
  CORE_SERVICE_SSL_STORE_PASSWORD: brain63b170eaefd57@ssl
  CORE_SERVICE_UCB_ADD_MONEY_BASE_URL: http://10.11.245.19/ucb/
  CORE_SERVICE_UCB_BASE_URL: http://10.11.245.19/ucb/
  CORE_SERVICE_UCB_SEND_MONEY_BASE_URL: http://10.11.245.19/ucb/
  CORE_SERVICE_ZONE: http://eureka-sts-0.eureka.default.svc.uat.pocket.local:8761/eureka
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  labels:
    app: core-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: core-service
        envFrom:
        - configMapRef:
            name: core-service
        image: 10.96.233.11:8888/pocket/core-service:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        ports:
        - containerPort: 8905
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8905
          initialDelaySeconds: 120
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8905
          initialDelaySeconds: 120
          periodSeconds: 3


        
---

apiVersion: v1
kind: Service
metadata:
  name: core-service-svc
spec:
  selector:
    app: core-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8905
 