apiVersion: v1
kind: ConfigMap
metadata:
  name: merchant-charge-config-service
data:
  MERCHANT_BULK_SERVICE_SERVER_PORT: '8914'
  MERCHANT_BULK_SERVICE_ZONE: http://eureka-sts-0.eureka.default.svc.uat.pocket.local:8761/eureka
  MERCHANT_BULK_SERVICE_DB_URL: jdbc:postgresql://10.11.245.12:5432/wallet_db?currentSchema=merchant
  MERCHANT_BULK_SERVICE_DB_USERNAME: pocket_uat
  MERCHANT_BULK_SERVICE_DB_PASSWORD: p0cket@ABG
  MERCHANT_BULK_SERVICE_REDIS_HOST: redis-1678904797-master.redis.svc.uat.pocket.local
  MERCHANT_BULK_SERVICE_REDIS_PORT: '6379'
  MERCHANT_BULK_SERVICE_REDIS_PASSWORD: p0cket@ABG
  MERCHANT_BULK_REDIS_POOL_MAX_CONNECTION: '30'
  MERCHANT_BULK_REDIS_POOL_MAX_IDLE_CONNECTION: '10'
  MERCHANT_BULK_REDIS_POOL_MIN_IDLE_CONNECTION: '0'
  MERCHANT_BULK_SERVICE_LOGBACK_FILE: classpath:log/logback-beta.xml
  MERCHANT_BULK_SERVICE_JWT_TOKEN_PREFIX: Bearer
  MERCHANT_BULK_SERVICE_JWT_TOKEN_EXPIRY_MINUTE: '30'
  MERCHANT_BULK_SERVICE_JWT_TOKEN_SECRET_KEY: 327234753778214125442A472D4B6150645367566B59703373367638792F423F
  MERCHANT_BULK_BAD_LOGIN_ATTEMPT: '3'
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant-charge-config-service
  labels:
    app: merchant-charge-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merchant-charge-config-service
  template:
    metadata:
      labels:
        app: merchant-charge-config-service
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name:  merchant-charge-config-service
        envFrom:
        - configMapRef:
            name:  merchant-charge-config-service
        image: 10.96.233.11:8888/pocket/merchant-charge-config-service:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        ports:
        - containerPort: 8914
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8914
          initialDelaySeconds: 120
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8914
          initialDelaySeconds: 120
          periodSeconds: 3


        
---

apiVersion: v1
kind: Service
metadata:
  name: merchant-charge-config-service-svc
spec:
  selector:
    app: merchant-charge-config-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8914
 