apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service 
data:
  NOTIFICATION_SERVICE_PORT: '0'
  NOTIFICATION_SERVICE_ZONE:  http://eureka-sts-0.eureka.default.svc.uat.pocket.local:8761/eureka
  NOTIFICATION_SERVICE_SLEUTH_SAM_PRO: '1.0'
  NOTIFICATION_SERVICE_DATASOURCE_URL: jdbc:postgresql://10.11.245.12:5432/wallet_db?currentSchema=notification
  NOTIFICATION_SERVICE_DATASOURCE_USERNAME: pocket_uat
  NOTIFICATION_SERVICE_DATASOURCE_PASSWORD: p0cket@ABG
  NOTIFICATION_SERVICE_MAIL_HOST: email-smtp.ap-southeast-1.amazonaws.com
  NOTIFICATION_SERVICE_MAIL_PORT: '587'
  NOTIFICATION_SERVICE_MAIL_USERNAME: AKIAWQPMH2PZNR75JZPF
  NOTIFICATION_SERVICE_MAIL_PASSWORD: BCjKqvwSdfUou+cwmRBU4Pt11UAYVjXIAs6jcNzG5iLJ
  NOTIFICATION_SERVICE_REDIS_HOST: redis-1678904797-master.redis.svc.uat.pocket.local
  NOTIFICATION_SERVICE_REDIS_PORT: '6379'
  NOTIFICATION_SERVICE_REDIS_PASSWORD: p0cket@ABG
  NOTIFICATION_SERVICE_REDIS_MAX_CONNECTION: '30'
  NOTIFICATION_SERVICE_REDIS_MAX_IDLE_CONNECTION: '2'
  NOTIFICATION_SERVICE_REDIS_MIN_IDLE_CONNECTION: '0'
  NOTIFICATION_SERVICE_LOGGING_CONFIG: classpath:log/logback-beta.xml
  NOTIFICATION_SERVICE_SSL_SMS_API_TOKEN: rmiwsmly-i2htfqwk-v2ly7o3o-mxkromd2-qsczwtws
  NOTIFICATION_SERVICE_SSL_SMS_API_TOKEN_OPERATOR_OTHER: ABGNONAPI
  NOTIFICATION_SERVICE_SSL_SMS_API_TOKEN_OPERATOR_GP: ABGNONAPI
  NOTIFICATION_SERVICE_NOT_TEMP_COMM_FOOTER: "Regards,\nPocket team, Bangladesh."
  NOTIFICATION_SERVICE_NOT_TEMP_COMM_SMS_TOKEN: "IGJlYdTAobC"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: notification-service
        envFrom:
        - configMapRef:
            name:  notification-service
        image: 10.96.233.11:8888/pocket/notification-service:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        ports:
        - containerPort: 8912
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8912
          initialDelaySeconds: 120
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8912
          initialDelaySeconds: 120
          periodSeconds: 3


        
---

apiVersion: v1
kind: Service
metadata:
  name: notification-service-svc
spec:
  selector:
    app: notification-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8912
 