apiVersion: v1
kind: ConfigMap
metadata:
  name: send-money-service 
data:
  PAYMENT_SERVICE_HIKARI_MAX_POOL_SIZE: '1'
  PAYMENT_SERVICE_HIKARI_MIN_IDLE: '1'
  SEND_MONEY_SERVICE_DATASOURCE_PASSWORD: p0cket@ABG
  SEND_MONEY_SERVICE_DATASOURCE_URL: jdbc:postgresql://10.11.245.12:5432/wallet_db?currentSchema=send_money
  SEND_MONEY_SERVICE_DATASOURCE_USERNAME: pocket_uat
  SEND_MONEY_SERVICE_LOGGING_CONFIG: classpath:log/logback-beta.xml
  SEND_MONEY_SERVICE_PORT: '8910'
  SEND_MONEY_SERVICE_REDIS_HOST: redis-1678904797-master.redis.svc.uat.pocket.local
  SEND_MONEY_SERVICE_REDIS_MAX_CONNECTION: '30'
  SEND_MONEY_SERVICE_REDIS_MAX_IDLE_CONNECTION: '2'
  SEND_MONEY_SERVICE_REDIS_MIN_IDLE_CONNECTION: '0'
  SEND_MONEY_SERVICE_REDIS_PASSWORD: p0cket@ABG
  SEND_MONEY_SERVICE_REDIS_PORT: '6379'
  SEND_MONEY_SERVICE_SLEUTH_SAM_PRO: '1.0'
  SEND_MONEY_SERVICE_ZONE: http://eureka-sts-0.eureka.default.svc.uat.pocket.local:8761/eureka
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-money-service
  labels:
    app: send-money-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send-money-service
  template:
    metadata:
      labels:
        app: send-money-service
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: send-money-service
        envFrom:
        - configMapRef:
            name: send-money-service
        image: 10.96.233.11:8888/pocket/send-money-service:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        ports:
        - containerPort: 8910
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8910
          initialDelaySeconds: 120
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8910
          initialDelaySeconds: 120
          periodSeconds: 3


        
---

apiVersion: v1
kind: Service
metadata:
  name: send-money-service-svc
spec:
  selector:
    app: send-money-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8910
 