apiVersion: v1
kind: ConfigMap
metadata:
  name: tfa-service 
data:
  EUREKA_PORT: '8761'
  TFA_SERVICE_DATASOURCE_PASSWORD: p0cket@ABG
  TFA_SERVICE_DATASOURCE_URL: jdbc:postgresql://10.11.245.12:5432/wallet_db?currentSchema=tfa
  TFA_SERVICE_DATASOURCE_USERNAME: pocket_uat
  TFA_SERVICE_IS_OTP_DUMMY_ALLOWED: 'True'
  TFA_SERVICE_LOGGING_CONFIG: classpath:log/logback-beta.xml
  TFA_SERVICE_PASSWORD_STRENGTH: '4'
  TFA_SERVICE_PORT: '8912'
  TFA_SERVICE_REDIS_HOST: redis-1678904797-master.redis.svc.uat.pocket.local
  TFA_SERVICE_REDIS_MAX_CONNECTION: '30'
  TFA_SERVICE_REDIS_MAX_IDLE_CONNECTION: '10'
  TFA_SERVICE_REDIS_MIN_IDLE_CONNECTION: '0'
  TFA_SERVICE_REDIS_PASSWORD: p0cket@ABG
  TFA_SERVICE_REDIS_PORT: '6379'
  TFA_SERVICE_ZONE: http://eureka-sts-0.eureka:8761/eureka,http://eureka-sts-1.eureka:8761/eureka,http://eureka-sts-2.eureka:8761/eureka
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfa-service
  labels:
    app: tfa-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfa-service
  template:
    metadata:
      labels:
        app: tfa-service
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name:  tfa-service
        envFrom:
        - configMapRef:
            name:  tfa-service
        image: 10.96.233.11:8888/pocket/tfa-service:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        ports:
        - containerPort: 8912
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8912
          initialDelaySeconds: 120
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8912
          initialDelaySeconds: 120
          periodSeconds: 3


        
---

apiVersion: v1
kind: Service
metadata:
  name: tfa-service-svc
spec:
  selector:
    app: tfa-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8912
 